// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: admin_movies_persons_service_v1_messages.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchPersonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullnameRU *string                `protobuf:"bytes,1,opt,name=fullnameRU,json=fullname_ru,proto3,oneof" json:"fullnameRU,omitempty"`
	FullnameEN *string                `protobuf:"bytes,2,opt,name=fullnameEN,json=fullname_en,proto3,oneof" json:"fullnameEN,omitempty"`
	Birthday   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=birthday,proto3,oneof" json:"birthday,omitempty"`
	Sex        *string                `protobuf:"bytes,4,opt,name=sex,proto3,oneof" json:"sex,omitempty"`
	Photo      []byte                 `protobuf:"bytes,5,opt,name=photo,proto3,oneof" json:"photo,omitempty"`
	// must be in range 10-100
	Limit int32 `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	// must be > 0
	Page int32 `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *SearchPersonRequest) Reset() {
	*x = SearchPersonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchPersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPersonRequest) ProtoMessage() {}

func (x *SearchPersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPersonRequest.ProtoReflect.Descriptor instead.
func (*SearchPersonRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_persons_service_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *SearchPersonRequest) GetFullnameRU() string {
	if x != nil && x.FullnameRU != nil {
		return *x.FullnameRU
	}
	return ""
}

func (x *SearchPersonRequest) GetFullnameEN() string {
	if x != nil && x.FullnameEN != nil {
		return *x.FullnameEN
	}
	return ""
}

func (x *SearchPersonRequest) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *SearchPersonRequest) GetSex() string {
	if x != nil && x.Sex != nil {
		return *x.Sex
	}
	return ""
}

func (x *SearchPersonRequest) GetPhoto() []byte {
	if x != nil {
		return x.Photo
	}
	return nil
}

func (x *SearchPersonRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchPersonRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type DeletePersonsResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeletedPersonIDs []string `protobuf:"bytes,1,rep,name=DeletedPersonIDs,json=deleted_persons_ids,proto3" json:"DeletedPersonIDs,omitempty"`
}

func (x *DeletePersonsResponce) Reset() {
	*x = DeletePersonsResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePersonsResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePersonsResponce) ProtoMessage() {}

func (x *DeletePersonsResponce) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePersonsResponce.ProtoReflect.Descriptor instead.
func (*DeletePersonsResponce) Descriptor() ([]byte, []int) {
	return file_admin_movies_persons_service_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *DeletePersonsResponce) GetDeletedPersonIDs() []string {
	if x != nil {
		return x.DeletedPersonIDs
	}
	return nil
}

type GetPersonsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// use ',' as separator
	PersonsIDs string `protobuf:"bytes,1,opt,name=PersonsIDs,json=persons_ids,proto3" json:"PersonsIDs,omitempty"`
	// must be in range 10-100
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// must be > 0
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *GetPersonsRequest) Reset() {
	*x = GetPersonsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPersonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonsRequest) ProtoMessage() {}

func (x *GetPersonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonsRequest.ProtoReflect.Descriptor instead.
func (*GetPersonsRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_persons_service_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GetPersonsRequest) GetPersonsIDs() string {
	if x != nil {
		return x.PersonsIDs
	}
	return ""
}

func (x *GetPersonsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPersonsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type CreatePersonResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PersonID string `protobuf:"bytes,1,opt,name=PersonID,json=person_id,proto3" json:"PersonID,omitempty"`
}

func (x *CreatePersonResponce) Reset() {
	*x = CreatePersonResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePersonResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersonResponce) ProtoMessage() {}

func (x *CreatePersonResponce) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersonResponce.ProtoReflect.Descriptor instead.
func (*CreatePersonResponce) Descriptor() ([]byte, []int) {
	return file_admin_movies_persons_service_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePersonResponce) GetPersonID() string {
	if x != nil {
		return x.PersonID
	}
	return ""
}

type UpdatePersonFieldsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// person id for updating
	ID         string                 `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	FullnameRU *string                `protobuf:"bytes,2,opt,name=fullnameRU,json=fullname_ru,proto3,oneof" json:"fullnameRU,omitempty"`
	FullnameEN *string                `protobuf:"bytes,3,opt,name=fullnameEN,json=fullname_en,proto3,oneof" json:"fullnameEN,omitempty"`
	Birthday   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=birthday,proto3,oneof" json:"birthday,omitempty"`
	Sex        *string                `protobuf:"bytes,5,opt,name=sex,proto3,oneof" json:"sex,omitempty"`
	Photo      []byte                 `protobuf:"bytes,6,opt,name=photo,proto3,oneof" json:"photo,omitempty"`
}

func (x *UpdatePersonFieldsRequest) Reset() {
	*x = UpdatePersonFieldsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePersonFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePersonFieldsRequest) ProtoMessage() {}

func (x *UpdatePersonFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePersonFieldsRequest.ProtoReflect.Descriptor instead.
func (*UpdatePersonFieldsRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_persons_service_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePersonFieldsRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdatePersonFieldsRequest) GetFullnameRU() string {
	if x != nil && x.FullnameRU != nil {
		return *x.FullnameRU
	}
	return ""
}

func (x *UpdatePersonFieldsRequest) GetFullnameEN() string {
	if x != nil && x.FullnameEN != nil {
		return *x.FullnameEN
	}
	return ""
}

func (x *UpdatePersonFieldsRequest) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *UpdatePersonFieldsRequest) GetSex() string {
	if x != nil && x.Sex != nil {
		return *x.Sex
	}
	return ""
}

func (x *UpdatePersonFieldsRequest) GetPhoto() []byte {
	if x != nil {
		return x.Photo
	}
	return nil
}

type UpdatePersonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// person id for updating
	ID         string                 `protobuf:"bytes,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	FullnameRU string                 `protobuf:"bytes,2,opt,name=fullnameRU,json=fullname_ru,proto3" json:"fullnameRU,omitempty"`
	FullnameEN string                 `protobuf:"bytes,3,opt,name=fullnameEN,json=fullname_en,proto3" json:"fullnameEN,omitempty"`
	Birthday   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Sex        string                 `protobuf:"bytes,5,opt,name=sex,proto3" json:"sex,omitempty"`
	Photo      []byte                 `protobuf:"bytes,6,opt,name=photo,proto3" json:"photo,omitempty"`
}

func (x *UpdatePersonRequest) Reset() {
	*x = UpdatePersonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePersonRequest) ProtoMessage() {}

func (x *UpdatePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePersonRequest.ProtoReflect.Descriptor instead.
func (*UpdatePersonRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_persons_service_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePersonRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdatePersonRequest) GetFullnameRU() string {
	if x != nil {
		return x.FullnameRU
	}
	return ""
}

func (x *UpdatePersonRequest) GetFullnameEN() string {
	if x != nil {
		return x.FullnameEN
	}
	return ""
}

func (x *UpdatePersonRequest) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *UpdatePersonRequest) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *UpdatePersonRequest) GetPhoto() []byte {
	if x != nil {
		return x.Photo
	}
	return nil
}

type CreatePersonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullnameRU string                 `protobuf:"bytes,1,opt,name=fullnameRU,json=fullname_ru,proto3" json:"fullnameRU,omitempty"`
	FullnameEN *string                `protobuf:"bytes,2,opt,name=fullnameEN,json=fullname_en,proto3,oneof" json:"fullnameEN,omitempty"`
	Birthday   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=birthday,proto3,oneof" json:"birthday,omitempty"`
	Sex        *string                `protobuf:"bytes,4,opt,name=sex,proto3,oneof" json:"sex,omitempty"`
	Photo      []byte                 `protobuf:"bytes,5,opt,name=photo,proto3,oneof" json:"photo,omitempty"`
}

func (x *CreatePersonRequest) Reset() {
	*x = CreatePersonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersonRequest) ProtoMessage() {}

func (x *CreatePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersonRequest.ProtoReflect.Descriptor instead.
func (*CreatePersonRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_persons_service_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePersonRequest) GetFullnameRU() string {
	if x != nil {
		return x.FullnameRU
	}
	return ""
}

func (x *CreatePersonRequest) GetFullnameEN() string {
	if x != nil && x.FullnameEN != nil {
		return *x.FullnameEN
	}
	return ""
}

func (x *CreatePersonRequest) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *CreatePersonRequest) GetSex() string {
	if x != nil && x.Sex != nil {
		return *x.Sex
	}
	return ""
}

func (x *CreatePersonRequest) GetPhoto() []byte {
	if x != nil {
		return x.Photo
	}
	return nil
}

type DeletePersonsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// use ',' as separator
	PersonsIDs string `protobuf:"bytes,1,opt,name=PersonsIDs,json=persons_ids,proto3" json:"PersonsIDs,omitempty"`
}

func (x *DeletePersonsRequest) Reset() {
	*x = DeletePersonsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePersonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePersonsRequest) ProtoMessage() {}

func (x *DeletePersonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePersonsRequest.ProtoReflect.Descriptor instead.
func (*DeletePersonsRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_persons_service_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePersonsRequest) GetPersonsIDs() string {
	if x != nil {
		return x.PersonsIDs
	}
	return ""
}

type IsPersonWithIDExistsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PersonExists bool `protobuf:"varint,1,opt,name=PersonExists,json=person_exists,proto3" json:"PersonExists,omitempty"`
}

func (x *IsPersonWithIDExistsResponse) Reset() {
	*x = IsPersonWithIDExistsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsPersonWithIDExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsPersonWithIDExistsResponse) ProtoMessage() {}

func (x *IsPersonWithIDExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsPersonWithIDExistsResponse.ProtoReflect.Descriptor instead.
func (*IsPersonWithIDExistsResponse) Descriptor() ([]byte, []int) {
	return file_admin_movies_persons_service_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *IsPersonWithIDExistsResponse) GetPersonExists() bool {
	if x != nil {
		return x.PersonExists
	}
	return false
}

type IsPersonWithIDExistsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PersonID string `protobuf:"bytes,1,opt,name=PersonID,json=person_id,proto3" json:"PersonID,omitempty"`
}

func (x *IsPersonWithIDExistsRequest) Reset() {
	*x = IsPersonWithIDExistsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsPersonWithIDExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsPersonWithIDExistsRequest) ProtoMessage() {}

func (x *IsPersonWithIDExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsPersonWithIDExistsRequest.ProtoReflect.Descriptor instead.
func (*IsPersonWithIDExistsRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_persons_service_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *IsPersonWithIDExistsRequest) GetPersonID() string {
	if x != nil {
		return x.PersonID
	}
	return ""
}

type IsPersonExistsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PersonExists     bool     `protobuf:"varint,1,opt,name=PersonExists,json=person_exists,proto3" json:"PersonExists,omitempty"`
	FindedPersonsIDs []string `protobuf:"bytes,2,rep,name=FindedPersonsIDs,json=finded_persons_ids,proto3" json:"FindedPersonsIDs,omitempty"`
}

func (x *IsPersonExistsResponse) Reset() {
	*x = IsPersonExistsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsPersonExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsPersonExistsResponse) ProtoMessage() {}

func (x *IsPersonExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsPersonExistsResponse.ProtoReflect.Descriptor instead.
func (*IsPersonExistsResponse) Descriptor() ([]byte, []int) {
	return file_admin_movies_persons_service_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *IsPersonExistsResponse) GetPersonExists() bool {
	if x != nil {
		return x.PersonExists
	}
	return false
}

func (x *IsPersonExistsResponse) GetFindedPersonsIDs() []string {
	if x != nil {
		return x.FindedPersonsIDs
	}
	return nil
}

type IsPersonExistsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullnameRU *string                `protobuf:"bytes,1,opt,name=fullnameRU,json=fullname_ru,proto3,oneof" json:"fullnameRU,omitempty"`
	FullnameEN *string                `protobuf:"bytes,2,opt,name=fullnameEN,json=fullname_en,proto3,oneof" json:"fullnameEN,omitempty"`
	Birthday   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=birthday,proto3,oneof" json:"birthday,omitempty"`
	Sex        *string                `protobuf:"bytes,4,opt,name=sex,proto3,oneof" json:"sex,omitempty"`
}

func (x *IsPersonExistsRequest) Reset() {
	*x = IsPersonExistsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsPersonExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsPersonExistsRequest) ProtoMessage() {}

func (x *IsPersonExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsPersonExistsRequest.ProtoReflect.Descriptor instead.
func (*IsPersonExistsRequest) Descriptor() ([]byte, []int) {
	return file_admin_movies_persons_service_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *IsPersonExistsRequest) GetFullnameRU() string {
	if x != nil && x.FullnameRU != nil {
		return *x.FullnameRU
	}
	return ""
}

func (x *IsPersonExistsRequest) GetFullnameEN() string {
	if x != nil && x.FullnameEN != nil {
		return *x.FullnameEN
	}
	return ""
}

func (x *IsPersonExistsRequest) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *IsPersonExistsRequest) GetSex() string {
	if x != nil && x.Sex != nil {
		return *x.Sex
	}
	return ""
}

type Person struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullnameRU string `protobuf:"bytes,1,opt,name=fullnameRU,json=fullname_ru,proto3" json:"fullnameRU,omitempty"`
	FullnameEN string `protobuf:"bytes,2,opt,name=fullnameEN,json=fullname_en,proto3" json:"fullnameEN,omitempty"`
	Birthday   string `protobuf:"bytes,3,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Sex        string `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	PhotoUrl   string `protobuf:"bytes,5,opt,name=photoUrl,json=photo_url,proto3" json:"photoUrl,omitempty"`
}

func (x *Person) Reset() {
	*x = Person{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_admin_movies_persons_service_v1_messages_proto_rawDescGZIP(), []int{12}
}

func (x *Person) GetFullnameRU() string {
	if x != nil {
		return x.FullnameRU
	}
	return ""
}

func (x *Person) GetFullnameEN() string {
	if x != nil {
		return x.FullnameEN
	}
	return ""
}

func (x *Person) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *Person) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *Person) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

type Persons struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Persons map[string]*Person `protobuf:"bytes,1,rep,name=persons,proto3" json:"persons,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Persons) Reset() {
	*x = Persons{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Persons) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Persons) ProtoMessage() {}

func (x *Persons) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Persons.ProtoReflect.Descriptor instead.
func (*Persons) Descriptor() ([]byte, []int) {
	return file_admin_movies_persons_service_v1_messages_proto_rawDescGZIP(), []int{13}
}

func (x *Persons) GetPersons() map[string]*Person {
	if x != nil {
		return x.Persons
	}
	return nil
}

type UserErrorMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UserErrorMessage) Reset() {
	*x = UserErrorMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserErrorMessage) ProtoMessage() {}

func (x *UserErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_admin_movies_persons_service_v1_messages_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserErrorMessage.ProtoReflect.Descriptor instead.
func (*UserErrorMessage) Descriptor() ([]byte, []int) {
	return file_admin_movies_persons_service_v1_messages_proto_rawDescGZIP(), []int{14}
}

func (x *UserErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_admin_movies_persons_service_v1_messages_proto protoreflect.FileDescriptor

var file_admin_movies_persons_service_v1_messages_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x5f, 0x70,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x76,
	0x31, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1c, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x5f, 0x70,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xb7, 0x02, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0a, 0x66, 0x75, 0x6c, 0x6c, 0x6e,
	0x61, 0x6d, 0x65, 0x52, 0x55, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x66,
	0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x75, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a,
	0x0a, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x45, 0x4e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x01, 0x52, 0x0b, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x6e,
	0x88, 0x01, 0x01, 0x12, 0x3b, 0x0a, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x48, 0x02, 0x52, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x88, 0x01, 0x01,
	0x12, 0x15, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52,
	0x03, 0x73, 0x65, 0x78, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x04, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x88,
	0x01, 0x01, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x42, 0x0d, 0x0a, 0x0b,
	0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x55, 0x42, 0x0d, 0x0a, 0x0b, 0x5f,
	0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x45, 0x4e, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x62,
	0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x73, 0x65, 0x78, 0x42,
	0x08, 0x0a, 0x06, 0x5f, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a, 0x15, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x63, 0x65, 0x12, 0x2d, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x13, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x5f, 0x69, 0x64,
	0x73, 0x22, 0x5e, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0a, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x73, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x73, 0x5f, 0x69, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x22, 0x33, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x08, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x22, 0xa3, 0x02, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0a, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65,
	0x52, 0x55, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x66, 0x75, 0x6c, 0x6c,
	0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x75, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a, 0x0a, 0x66, 0x75,
	0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x45, 0x4e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x0b, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x88, 0x01, 0x01,
	0x12, 0x3b, 0x0a, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x02,
	0x52, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x88, 0x01, 0x01, 0x12, 0x15, 0x0a,
	0x03, 0x73, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x03, 0x73, 0x65,
	0x78, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0c, 0x48, 0x04, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x88, 0x01, 0x01, 0x42,
	0x0d, 0x0a, 0x0b, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x55, 0x42, 0x0d,
	0x0a, 0x0b, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x45, 0x4e, 0x42, 0x0b, 0x0a,
	0x09, 0x5f, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x73,
	0x65, 0x78, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x22, 0xc7, 0x01, 0x0a,
	0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0a, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65,
	0x52, 0x55, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61,
	0x6d, 0x65, 0x5f, 0x72, 0x75, 0x12, 0x1f, 0x0a, 0x0a, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d,
	0x65, 0x45, 0x4e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x75, 0x6c, 0x6c, 0x6e,
	0x61, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x12, 0x36, 0x0a, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64,
	0x61, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x78,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x22, 0xf9, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f,
	0x0a, 0x0a, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x55, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x75, 0x12,
	0x24, 0x0a, 0x0a, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x45, 0x4e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x5f,
	0x65, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x3b, 0x0a, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x48, 0x01, 0x52, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x88,
	0x01, 0x01, 0x12, 0x15, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x02, 0x52, 0x03, 0x73, 0x65, 0x78, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x70, 0x68, 0x6f,
	0x74, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x03, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x74,
	0x6f, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d,
	0x65, 0x45, 0x4e, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79,
	0x42, 0x06, 0x0a, 0x04, 0x5f, 0x73, 0x65, 0x78, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x70, 0x68, 0x6f,
	0x74, 0x6f, 0x22, 0x37, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0a, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x73, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x5f, 0x69, 0x64, 0x73, 0x22, 0x43, 0x0a, 0x1c, 0x49,
	0x73, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x57, 0x69, 0x74, 0x68, 0x49, 0x44, 0x45, 0x78, 0x69,
	0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0d, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x5f, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73,
	0x22, 0x3a, 0x0a, 0x1b, 0x49, 0x73, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x57, 0x69, 0x74, 0x68,
	0x49, 0x44, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x08, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x22, 0x6b, 0x0a, 0x16,
	0x49, 0x73, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x70, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x5f, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x2c, 0x0a, 0x10, 0x46,
	0x69, 0x6e, 0x64, 0x65, 0x64, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x49, 0x44, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x12, 0x66, 0x69, 0x6e, 0x64, 0x65, 0x64, 0x5f, 0x70, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x73, 0x5f, 0x69, 0x64, 0x73, 0x22, 0xea, 0x01, 0x0a, 0x15, 0x49, 0x73,
	0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0a, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x52,
	0x55, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x66, 0x75, 0x6c, 0x6c, 0x6e,
	0x61, 0x6d, 0x65, 0x5f, 0x72, 0x75, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a, 0x0a, 0x66, 0x75, 0x6c,
	0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x45, 0x4e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x0b, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x88, 0x01, 0x01, 0x12,
	0x3b, 0x0a, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x02, 0x52,
	0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x88, 0x01, 0x01, 0x12, 0x15, 0x0a, 0x03,
	0x73, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x03, 0x73, 0x65, 0x78,
	0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65,
	0x52, 0x55, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x45,
	0x4e, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x42, 0x06,
	0x0a, 0x04, 0x5f, 0x73, 0x65, 0x78, 0x22, 0x95, 0x01, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x12, 0x1f, 0x0a, 0x0a, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x55, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x5f,
	0x72, 0x75, 0x12, 0x1f, 0x0a, 0x0a, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x45, 0x4e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65,
	0x5f, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65,
	0x78, 0x12, 0x1b, 0x0a, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x55, 0x72, 0x6c, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x5f, 0x75, 0x72, 0x6c, 0x22, 0xb9,
	0x01, 0x0a, 0x07, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x12, 0x4c, 0x0a, 0x07, 0x70, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x5f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x5f, 0x70, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x73, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x1a, 0x60, 0x0a, 0x0c, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x3a, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x5f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x5f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x2c, 0x0a, 0x10, 0x55, 0x73,
	0x65, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x28, 0x5a, 0x26, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x5f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x5f, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_admin_movies_persons_service_v1_messages_proto_rawDescOnce sync.Once
	file_admin_movies_persons_service_v1_messages_proto_rawDescData = file_admin_movies_persons_service_v1_messages_proto_rawDesc
)

func file_admin_movies_persons_service_v1_messages_proto_rawDescGZIP() []byte {
	file_admin_movies_persons_service_v1_messages_proto_rawDescOnce.Do(func() {
		file_admin_movies_persons_service_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_admin_movies_persons_service_v1_messages_proto_rawDescData)
	})
	return file_admin_movies_persons_service_v1_messages_proto_rawDescData
}

var file_admin_movies_persons_service_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_admin_movies_persons_service_v1_messages_proto_goTypes = []interface{}{
	(*SearchPersonRequest)(nil),          // 0: admin_movies_persons_service.SearchPersonRequest
	(*DeletePersonsResponce)(nil),        // 1: admin_movies_persons_service.DeletePersonsResponce
	(*GetPersonsRequest)(nil),            // 2: admin_movies_persons_service.GetPersonsRequest
	(*CreatePersonResponce)(nil),         // 3: admin_movies_persons_service.CreatePersonResponce
	(*UpdatePersonFieldsRequest)(nil),    // 4: admin_movies_persons_service.UpdatePersonFieldsRequest
	(*UpdatePersonRequest)(nil),          // 5: admin_movies_persons_service.UpdatePersonRequest
	(*CreatePersonRequest)(nil),          // 6: admin_movies_persons_service.CreatePersonRequest
	(*DeletePersonsRequest)(nil),         // 7: admin_movies_persons_service.DeletePersonsRequest
	(*IsPersonWithIDExistsResponse)(nil), // 8: admin_movies_persons_service.IsPersonWithIDExistsResponse
	(*IsPersonWithIDExistsRequest)(nil),  // 9: admin_movies_persons_service.IsPersonWithIDExistsRequest
	(*IsPersonExistsResponse)(nil),       // 10: admin_movies_persons_service.IsPersonExistsResponse
	(*IsPersonExistsRequest)(nil),        // 11: admin_movies_persons_service.IsPersonExistsRequest
	(*Person)(nil),                       // 12: admin_movies_persons_service.Person
	(*Persons)(nil),                      // 13: admin_movies_persons_service.Persons
	(*UserErrorMessage)(nil),             // 14: admin_movies_persons_service.UserErrorMessage
	nil,                                  // 15: admin_movies_persons_service.Persons.PersonsEntry
	(*timestamppb.Timestamp)(nil),        // 16: google.protobuf.Timestamp
}
var file_admin_movies_persons_service_v1_messages_proto_depIdxs = []int32{
	16, // 0: admin_movies_persons_service.SearchPersonRequest.birthday:type_name -> google.protobuf.Timestamp
	16, // 1: admin_movies_persons_service.UpdatePersonFieldsRequest.birthday:type_name -> google.protobuf.Timestamp
	16, // 2: admin_movies_persons_service.UpdatePersonRequest.birthday:type_name -> google.protobuf.Timestamp
	16, // 3: admin_movies_persons_service.CreatePersonRequest.birthday:type_name -> google.protobuf.Timestamp
	16, // 4: admin_movies_persons_service.IsPersonExistsRequest.birthday:type_name -> google.protobuf.Timestamp
	15, // 5: admin_movies_persons_service.Persons.persons:type_name -> admin_movies_persons_service.Persons.PersonsEntry
	12, // 6: admin_movies_persons_service.Persons.PersonsEntry.value:type_name -> admin_movies_persons_service.Person
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_admin_movies_persons_service_v1_messages_proto_init() }
func file_admin_movies_persons_service_v1_messages_proto_init() {
	if File_admin_movies_persons_service_v1_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_admin_movies_persons_service_v1_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchPersonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_persons_service_v1_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePersonsResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_persons_service_v1_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPersonsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_persons_service_v1_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePersonResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_persons_service_v1_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePersonFieldsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_persons_service_v1_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePersonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_persons_service_v1_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePersonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_persons_service_v1_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePersonsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_persons_service_v1_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsPersonWithIDExistsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_persons_service_v1_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsPersonWithIDExistsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_persons_service_v1_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsPersonExistsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_persons_service_v1_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsPersonExistsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_persons_service_v1_messages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_persons_service_v1_messages_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Persons); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_movies_persons_service_v1_messages_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserErrorMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_admin_movies_persons_service_v1_messages_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_admin_movies_persons_service_v1_messages_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_admin_movies_persons_service_v1_messages_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_admin_movies_persons_service_v1_messages_proto_msgTypes[11].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_admin_movies_persons_service_v1_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_admin_movies_persons_service_v1_messages_proto_goTypes,
		DependencyIndexes: file_admin_movies_persons_service_v1_messages_proto_depIdxs,
		MessageInfos:      file_admin_movies_persons_service_v1_messages_proto_msgTypes,
	}.Build()
	File_admin_movies_persons_service_v1_messages_proto = out.File
	file_admin_movies_persons_service_v1_messages_proto_rawDesc = nil
	file_admin_movies_persons_service_v1_messages_proto_goTypes = nil
	file_admin_movies_persons_service_v1_messages_proto_depIdxs = nil
}
